language: cpp

before_install:
  - pip install --user cpp-coveralls

script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target test -- ARGS=--verbose
- _build/check
  
after_success:
  - coveralls --root _build -E ".*gtest.*" -E ".*CMakeFiles.*"
